
#
# Usage:
# str2Color(<color> <variable> [REVERSE])
# sourrounds a string with escape sequences. Example:
#
# Example:
# set(foo "Wow my text")
# str2Color(Red foo)
# # then foo will be: "\x1b[31mWow my Text\x1b[m"
# - REVERSE: will first put the color reset, then the color
# # then foo will be: "\x1b[mWow my Text\x1b[31m")
#function(str2color s2c_type var)
#    if(NOT WIN32)
#        string(ASCII 27 Esc)
#        set(ColourReset "${Esc}[m")
#        set(ColourBold "${Esc}[1m")
#        set(Red "${Esc}[31m")
#        set(Green "${Esc}[32m")
#        set(Yellow "${Esc}[33m")
#        set(Blue "${Esc}[34m")
#        set(Magenta "${Esc}[35m")
#        set(Cyan "${Esc}[36m")
#        set(White "${Esc}[37m")
#        set(BoldRed "${Esc}[1;31m")
#        set(BoldGreen "${Esc}[1;32m")
#        set(BoldYellow "${Esc}[1;33m")
#        set(BoldBlue "${Esc}[1;34m")
#        set(BoldMagenta "${Esc}[1;35m")
#        set(BoldCyan "${Esc}[1;36m")
#        set(BoldWhite "${Esc}[1;37m")
#    endif()
#
#    if(DEFINED ${s2c_type})
#        if(ARGN STREQUAL REVERSE)
#            set(${var} ${ColourReset}${${var}}${${s2c_type}} PARENT_SCOPE)
#        else()
#            set(${var} ${${s2c_type}}${${var}}${ColourReset} PARENT_SCOPE)
#        endif()
#    endif()
#endfunction()

macro(print_color NAME)
    printc("        ${NAME}" COLOR ${NAME})
endmacro()

function(text)
    cmake_parse_arguments(PARSE_ARGV 0 "_TEXT" "BOLD" "COLOR" "")
    set(_TEXT_OPTIONS -E cmake_echo_color --no-newline)
    set(rest ${_TEXT_UNPARSED_ARGUMENTS})

    list(LENGTH _TEXT_UNPARSED_ARGUMENTS num)
    if(num EQUAL 1)
        if(NOT DEFINED ${_TEXT_UNPARSED_ARGUMENTS})
        else()
            set(string_var ${${_TEXT_UNPARSED_ARGUMENTS}})
            set(out_var ${_TEXT_UNPARSED_ARGUMENTS})
        endif()
    else()
        list(POP_BACK _TEXT_UNPARSED_ARGUMENTS out_var)
        set(string_var ${_TEXT_UNPARSED_ARGUMENTS})
    endif()

    if(_TEXT_COLOR)
        string(TOLOWER "${_TEXT_COLOR}" _TEXT_COLOR_LOWER)
        if(NOT ${_TEXT_COLOR_LOWER} MATCHES "^normal|black|red|green|yellow|blue|magenta|cyan|white")
            message(WARNING " Color ${_TEXT_COLOR} is not support. ")
            message(" Only these colours are supported: ... ")
            print_color(NORMAL)
            print_color(BLACK)
            print_color(RED)
            print_color(GREEN)
            print_color(YELLOW)
            print_color(BLUE)
            print_color(MAGENTA)
            print_color(CYAN)
            print_color(WHITE)
            return()
        else()
            list(APPEND _TEXT_OPTIONS --${_TEXT_COLOR_LOWER})
        endif()
    endif()

    if(_TEXT_BOLD)
        list(APPEND _TEXT_OPTIONS --bold)
    endif()

    foreach(s ${string_var})
        # message(++${s})
        if(${CMAKE_VERSION} LESS 3.15)
            execute_process(COMMAND ${CMAKE_COMMAND} -E env CLICOLOR_FORCE=1 ${CMAKE_COMMAND} ${_TEXT_OPTIONS} "${s}"
                OUTPUT_VARIABLE _TEXT_RESULT
            )
        else ()
            execute_process(COMMAND ${CMAKE_COMMAND} -E env CLICOLOR_FORCE=1 ${CMAKE_COMMAND} ${_TEXT_OPTIONS} "${s}"
                OUTPUT_VARIABLE _TEXT_RESULT
                # ECHO_ERROR_VARIABLE
                # ECHO_OUTPUT_VARIABLE
            )
        endif ()
        # message(--${_TEXT_RESULT})
        list(APPEND TEXT_RESULT_L ${_TEXT_RESULT})
    endforeach()
    # message(**${TEXT_RESULT_L})

    set(TEXT_RESULT ${TEXT_RESULT_L} PARENT_SCOPE)
    set(TEXT_VAR ${out_var} PARENT_SCOPE)
    set(TEXT_FAIL TRUE PARENT_SCOPE)
endfunction()
unset(print_color)

function(printc inText)
    text(${ARGN} inText)
#        message(" >>>> ARGN: ${ARGN}")
#        message(" >>>> TEXT_RESULT: ${TEXT_RESULT}")
#        message(" >>>> TEXT_VAR: ${TEXT_VAR}")
#        message(" >>>> ${TEXT_VAR}: ${${TEXT_VAR}}")
    message("${TEXT_RESULT} ")
endfunction()
function(str2color)
    text(${ARGN})
#    message(" >>>> ARGN: ${ARGN}")
#    message(" >>>> TEXT_RESULT: ${TEXT_RESULT}")
#    message(" >>>> TEXT_VAR: ${TEXT_VAR}")
#    message(" >>>> ${TEXT_VAR}: ${${TEXT_VAR}}")
    set(${TEXT_VAR} ${TEXT_RESULT} PARENT_SCOPE)
    set(str2color_FAIL ${TEXT_FAIL} PARENT_SCOPE)
endfunction()

#printc(COLOR NORMAL TEST_NORMAL)
#printc(BOLD COLOR NORMAL TEST_NORMAL_BOLD)
#printc(COLOR BLACK TEST_BLACK)
#printc(BOLD COLOR BLACK TEST_BLACK_BOLD)
#printc(COLOR RED TEST_RED)
#printc(BOLD COLOR RED TEST_RED_BOLD)
#printc(COLOR GREEN TEST_GREEN)
#printc(BOLD COLOR GREEN TEST_GREEN_BOLD)
#printc(COLOR YELLOW TEST_YELLOW)
#printc(BOLD COLOR YELLOW TEST_YELLOW_BOLD)
#printc(COLOR BLUE TEST_BLUE)
#printc(BOLD COLOR BLUE TEST_BLUE_BOLD)
#printc(COLOR MAGENTA TEST_MAGENTA)
#printc(BOLD COLOR MAGENTA TEST_MAGENTA_BOLD)
#printc(COLOR CYAN TEST_CYAN)
#printc(BOLD COLOR CYAN TEST_CYAN_BOLD)
#printc(COLOR WHITE TEST_WHITE)
#printc(BOLD COLOR WHITE TEST_WHITE_BOLD )

#
# Usage:
# toCamelCase(<variable|list> <out> [UPPER])
function(toCamelCase)
    cmake_parse_arguments(p "UPPER" "" "" ${ARGN})
    list(POP_BACK p_UNPARSED_ARGUMENTS cc_out)
    set(cc_list_in ${p_UNPARSED_ARGUMENTS})
    # check if cc_list_in is a variable
    list(LENGTH cc_list_in num)
    if(num EQUAL 1)
        if(DEFINED ${cc_list_in})
            set(cc_list_in ${${cc_list_in}})
        endif()
    else()
    endif()
    # check for UpperCamelCase
    if(NOT p_UPPER)
        # first folder stay lowerCase
        list(GET cc_list_in 0 cc_name)
        # remaining folders will be PascalCased
        string(TOLOWER ${cc_name} cc_name)
        list(SUBLIST cc_list_in 1 -1 cc_list_in)
    endif()

    foreach(str ${cc_list_in})
        string(TOLOWER ${str} str)
        string(SUBSTRING ${str} 0 1 FIRST_LETTER)
        string(SUBSTRING ${str} 1 -1 REST)
        string(TOUPPER ${FIRST_LETTER} FIRST_LETTER)
        set(pc_name ${pc_name}${FIRST_LETTER}${REST})
    endforeach()

    set(${cc_out} ${cc_name}${pc_name} PARENT_SCOPE)
endfunction()


#
# Usage:
# pathToCamelCase(<variable|string> <out> [UPPER])
function(pathToCamelCase)
    cmake_parse_arguments(p "UPPER" "" "" ${ARGN})
    list(POP_BACK p_UNPARSED_ARGUMENTS out)
    set(pathString ${p_UNPARSED_ARGUMENTS})
    if(DEFINED ${pathString})
        set(pathString ${${pathString}})
    endif()
    file(TO_CMAKE_PATH ${pathString} pathString)
    string(REPLACE "/" ";" pathList "${pathString}")
    if("${pathList}" MATCHES "^;.*")
        list(POP_FRONT pathList)
    endif()

    list(FILTER pathList EXCLUDE REGEX "\\.\\.")
    if(p_UPPER)
        toCamelCase(pathList output UPPER)
    else()
        toCamelCase(pathList output)
    endif()
    set(${out} ${output} PARENT_SCOPE)
endfunction()


# replace home dir by '~'
#
# Usage:
# shortPath(<path|variable> <out> [ALL])
#
# ALL: shortens every folder name to three letters except the last one
#
#      example: /home/<user>/my/nicest/folder
#           ->  ~/my/nic…/folder
#
#      example: /home/<user>/my/nicest/places/to/file.log
#           ->  ~/my/nic…/pla…/to/file.log
function(shortPath path out)
    cmake_parse_arguments(p "ALL" "" "" ${ARGN})
    list(LENGTH path num)
    if(num EQUAL 1)
        if(DEFINED ${path})
            set(path ${${path}})
        endif()
    endif()
    # if starts with windows volume (eg. C:)
    if(path MATCHES "^[a-zA-Z]:")
        file(TO_CMAKE_PATH ${path} path)
        string(REPLACE ";" ":" path "${path}")
    else()
        file(TO_CMAKE_PATH ${path} path)
    endif()
    string(REPLACE $ENV{HOME}/ "" _path ${path})
    if(NOT _path STREQUAL path)
        set(prefix ~/)
    else()
        string(SUBSTRING ${path} 0 1 sub)
        if(sub STREQUAL "/")
            set(prefix "/")
        endif()
    endif()
    if(p_ALL)
        string(REPLACE "/" ";" _path ${_path})
        list(POP_BACK _path last)
        foreach(dir ${_path})
            string(LENGTH ${dir} num)
            if(num GREATER 3)
            string(SUBSTRING ${dir} 0 3 dir)
            list(APPEND newPath ${dir}…)
            else()
            list(APPEND newPath ${dir})
            endif()
        endforeach()
        set(_path "${newPath};${last}")
        string(JOIN "/" _path ${_path})
    else()
        if(sub STREQUAL "/")
            set(prefix "")
        endif()
    endif()
    set(_path "${prefix}${_path}")
    set(${out} ${_path} PARENT_SCOPE)
endfunction()

if(WITH_CMAKE_UTILS_DEMO)
    set(LOG_FILENAME ${CMAKE_BINARY_DIR}/stringTools.log)
    set(WITH_LOGGING TRUE)
    include(${CMAKE_CURRENT_LIST_DIR}/log.cmake)

    message("\n===========================")
    message("  stringTools.cmake Demo")
    message("===========================\n")

    str2color(COLOR orange CMAKE_BUILD_TYPE BOLD)
    
    ####################
    ## toCamelCase UPPER
    message("-----------")
    message(" ")
    set(_variable "output_variable")
    str2color(COLOR green _variable BOLD)
    set(_home $ENV{HOME})
    set(ENV{HOME} /home/CMakePowerUser)

    toCamelCase("this;is;an;unconventional;LIST;of;words" output_variable UPPER)
    message("toCamelCase(\"this\;is\;an\;unconventional\;LIST\;of\;words\" output_variable UPPER)")
    str2color(COLOR green output_variable)
    message(">> ${_variable} = '${output_variable}'\n")

    set(input_list this is an unconventional LIST of words)
    toCamelCase(input_list output_variable UPPER)
    message("set(input_list this is an unconventional LIST of words)\ntoCamelCase(input_list output_variable UPPER)")
    str2color(COLOR green output_variable)
    message(">> ${_variable} = '${output_variable}'\n")

    message("toCamelCase(this is an unconventional LIST of words output_variable UPPER)")
    toCamelCase(this is an unconventional list of words output_variable UPPER)
    str2color(COLOR green output_variable)
    message(">> ${_variable} = '${output_variable}'\n")

    ####################
    ## toCamelCase
    message("-----------")
    message("toCamelCase(this is an unconventional list of words output_variable)")
    toCamelCase(this is an unconventional list of words output_variable)
    str2color(COLOR green output_variable)
    message(">> ${_variable} = '${output_variable}'\n")

    ####################
    ## pathToCamelCase
    set(longPath "/home/CMakePowerUser/Documents/development/magical_project_environment/cmake_modules")
    set(_srcDir ${CMAKE_SOURCE_DIR})
    set(CMAKE_SOURCE_DIR /home/CMakePowerUser/Documents/development/magical_project_environment/cmake-tools/test)

    message("-----------")
    set(myPath CMakePowerUser/Documents/development)
    set(_tmpSrc ${myPath})
    str2color(COLOR magenta _tmpSrc)
    set(_tmp myPath)
    str2color(_tmp COLOR magenta BOLD)
    pathToCamelCase(myPath output_variable)
    str2color(COLOR green output_variable)
    message("set(myPath CMakePowerUser/Documents/development)")
    message("pathToCamelCase(myPath output_variable)")
    message(">> ${_tmp} = '${_tmpSrc}'")
    message(">> ${_variable} = '${output_variable}'\n")
    pathToCamelCase(myPath output_variable UPPER)
    str2color(COLOR green output_variable)
    message("pathToCamelCase(CMakePowerUser/Documents/development output_variable UPPER)")
    message(">> ${_variable} = '${output_variable}'\n")
    pathToCamelCase(CMakePowerUser/Documents/development output_variable)
    str2color(COLOR green output_variable)
    message("pathToCamelCase(CMakePowerUser/Documents/development output_variable)")
    message(">> ${_variable} = '${output_variable}'\n")

    ####################
    ## shortPath
    message("-----------")
    shortPath("/home/CMakePowerUser/Documents/development/magical_project_environment/cmake_modules" output_variable)
    str2color(COLOR green output_variable)
    message("shortPath(\"/home/CMakePowerUser/Documents/development/magical_project_environment/cmake_modules\" output_variable)")
    message(">> ${_variable} = '${output_variable}'\n")

    shortPath("./Documents/development/magical_project_environment/cmake_modules" output_variable)
    str2color(COLOR green output_variable)
    message("shortPath(\"./Documents/development/magical_project_environment/cmake_modules\" output_variable)")
    message(">> ${_variable} = '${output_variable}'\n")
    shortPath("Documents/development/magical_project_environment/cmake_modules" output_variable)
    str2color(COLOR green output_variable)
    message("shortPath(\"Documents/development/magical_project_environment/cmake_modules\" output_variable)")
    message(">> ${_variable} = '${output_variable}'\n")

    shortPath("C:\\Programm Files\\Kitware\\CMake" output_variable)
    str2color(COLOR green output_variable)
    message("shortPath(\"C:\\Programm Files\\Kitware\\CMake\" output_variable)")
    message(">> ${_variable} = '${output_variable}'\n")
    shortPath("C:\\Programm Files\\Kitware\\CMake" output_variable ALL)
    str2color(COLOR green output_variable)
    message("shortPath(\"C:\\Programm Files\\Kitware\\CMake\" output_variable ALL)")
    message(">> ${_variable} = '${output_variable}'\n")

    set(ENV{HOME} "C:/Users/CMakePowerUser")
    shortPath("C:\\Users\\CMakePowerUser\\Documents\\development\\magical_project_environment\\cmake_modules" output_variable)
    message("shortPath(\"C:\\Users\\CMakePowerUser\\Documents\\development\\magical_project_environment\\cmake_modules\" output_variable)")
    str2color(COLOR green output_variable)
    message(">> ${_variable} = '${output_variable}'\n")
    shortPath("C:\\Users\\CMakePowerUser\\Documents\\development\\magical_project_environment\\cmake_modules" output_variable ALL)
    message("shortPath(\"C:\\Users\\CMakePowerUser\\Documents\\development\\magical_project_environment\\cmake_modules\" output_variable ALL)")
    str2color(COLOR green output_variable)
    message(">> ${_variable} = '${output_variable}'\n")
    # shortPath(CMAKE_CURRENT_LIST_DIR output_variable ALL)
    # message("shortPath(CMAKE_CURRENT_LIST_DIR output_variable ALL)")
    # str2color(COLOR green output_variable)
    # message(">> ${_variable} = '${output_variable}'\n")

    set(ENV{HOME} ${_home})
    flushLog()
    convert2Html()

    set(WITH_LOGGING OFF)
    set(LOG_FILENAME NONE)
    unset(LOG_FILENAME)
endif()
